//  :copyright: (c) 2014 Ruslan Baratov.
//  :copyright: (c) 2017 Alex Huszagh.
//  :license: BSD-2, see LICENSE.md for more details.
/*
 *  \addtogroup Warnings
 *  \brief Suppress all warnings.
 */

#pragma once

#include <warnings/arc-bridge-casts-disallowed-in-nonarc.h>
#include <warnings/arc-repeated-use-of-weak.h>
#include <warnings/assign-base-inaccessible.h>
#include <warnings/assign-could-not-be-generated.h>
#include <warnings/automatic-inline.h>
#include <warnings/behavior-change.h>
#include <warnings/bool-conversion.h>
#include <warnings/c++11-extensions.h>
#include <warnings/c++98-compat.h>
#include <warnings/c++98-compat-pedantic.h>
#include <warnings/cast-align.h>
#include <warnings/catch-semantic-changed.h>
#include <warnings/conditional-uninitialized.h>
#include <warnings/constant-conditional.h>
#include <warnings/constant-conversion.h>
#include <warnings/conversion.h>
#include <warnings/conversion-loss.h>
#include <warnings/conversion-sign-extended.h>
#include <warnings/copy-ctor-could-not-be-generated.h>
#include <warnings/deprecated.h>
#include <warnings/deprecated-declarations.h>
//#include <leathers/deprecated-implementations>

//#include <leathers/dflt-ctor-base-inaccessible>
//#include <leathers/dflt-ctor-could-not-be-generated>
//#include <leathers/user-ctor-required>
//#include <leathers/force-not-inlined>
//#include <leathers/not-inlined>
//#include <leathers/unreferenced-inline>
//#include <leathers/covered-switch-default>
//#include <leathers/deprecated-objc-isa-usage>
//#include <leathers/deprecated-register>
//#include <leathers/digraphs-not-supported>
//#include <leathers/disabled-macro-expansion>
//#include <leathers/documentation>
//#include <leathers/documentation-unknown-command>
//#include <leathers/empty-body>
//#include <leathers/enum-conversion>
//#include <leathers/exit-time-destructors>
//#include <leathers/extra-semi>
//#include <leathers/format>
//#include <leathers/four-char-constants>
//#include <leathers/global-constructors>
//#include <leathers/ill-formed-comma-expr>
//#include <leathers/implicit-fallthrough>
//#include <leathers/inherits-via-dominance>
//#include <leathers/int-conversion>
//#include <leathers/invalid-offsetof>
//#include <leathers/is-defined-to-be>
//#include <leathers/layout-changed>
//#include <leathers/missing-braces>
//#include <leathers/missing-field-initializers>
//#include <leathers/missing-noreturn>
//#include <leathers/missing-prototypes>
//#include <leathers/name-length-exceeded>
//#include <leathers/newline-eof>
//#include <leathers/no-such-warning>
//#include <leathers/non-virtual-dtor>
//#include <leathers/object-layout-change>
//#include <leathers/old-style-cast>
//#include <leathers/overloaded-virtual>
//#include <leathers/padded>
//#include <leathers/parentheses>
//#include <leathers/pedantic>
//#include <leathers/pointer-sign>
//#include <leathers/return-type>
//#include <leathers/shadow>
//#include <leathers/shift-sign-overflow>
//#include <leathers/shorten-64-to-32>
//#include <leathers/sign-compare>
//#include <leathers/sign-conversion>
//#include <leathers/signed-unsigned-compare>
//#include <leathers/static-ctor-not-thread-safe>
//#include <leathers/switch>
//#include <leathers/switch-enum>
//#include <leathers/this-used-in-init>
//#include <leathers/undef>
//#include <leathers/uninitialized>
//#include <leathers/unknown-pragmas>
//#include <leathers/unreachable-code>
//#include <leathers/unreachable-code-return>
//#include <leathers/unsafe-conversion>
//#include <leathers/unused-but-set-variable>
//#include <leathers/unused-function>
//#include <leathers/unused-label>
//#include <leathers/unused-parameter>
//#include <leathers/unused-value>
//#include <leathers/unused-variable>
//#include <leathers/used-but-marked-unused>
//#include <leathers/weak-vtables>
//#include <leathers/duplicate-method-match>
//#include <leathers/explicit-ownership-type>
//#include <leathers/implicit-atomic-properties>
//#include <leathers/implicit-retain-self>
//#include <leathers/objc-missing-property-synthesis>
//#include <leathers/objc-root-class>
//#include <leathers/protocol>
//#include <leathers/receiver-is-weak>
//#include <leathers/selector>
//#include <leathers/strict-selector-match>
//#include <leathers/undeclared-selector>
