//  :copyright: (c) 2014 Ruslan Baratov.
//  :copyright: (c) 2017 Alex Huszagh.
//  :license: BSD-2, see LICENSE.md for more details.
/*
 *  \addtogroup Warnings
 *  \brief Suppress all warnings.
 */

#pragma once

#include <warnings/arc-bridge-casts-disallowed-in-nonarc.h>
#include <warnings/arc-repeated-use-of-weak.h>
#include <warnings/assign-base-inaccessible.h>
#include <warnings/assign-could-not-be-generated.h>
#include <warnings/automatic-inline.h>
#include <warnings/behavior-change.h>
#include <warnings/bool-conversion.h>
#include <warnings/c++11-extensions.h>
#include <warnings/c++98-compat.h>
#include <warnings/c++98-compat-pedantic.h>
#include <warnings/cast-align.h>
#include <warnings/catch-semantic-changed.h>
#include <warnings/conditional-uninitialized.h>
#include <warnings/constant-conditional.h>
#include <warnings/constant-conversion.h>
#include <warnings/conversion.h>
#include <warnings/conversion-loss.h>
#include <warnings/conversion-sign-extended.h>
#include <warnings/copy-ctor-could-not-be-generated.h>
#include <warnings/deprecated.h>
#include <warnings/deprecated-declarations.h>
#include <warnings/deprecated-implementations.h>
#include <warnings/deprecated-objc-isa-usage.h>
#include <warnings/deprecated-register.h>
#include <warnings/dflt-ctor-base-inaccessible.h>
#include <warnings/dflt-ctor-could-not-be-generated.h>
#include <warnings/disabled-macro-expansion.h>
#include <warnings/documentation.h>
#include <warnings/documentation-unknown-command.h>
#include <warnings/duplicate-method-match.h>
#include <warnings/empty-body.h>
#include <warnings/enum-conversion.h>
#include <warnings/exit-time-destructors.h>
#include <warnings/explicit-ownership-type.h>
#include <warnings/extra-semi.h>
#include <warnings/force-not-inlined.h>
#include <warnings/format.h>
#include <warnings/four-char-constants.h>
#include <warnings/global-constructors.h>
#include <warnings/ill-formed-comma-expr.h>
#include <warnings/implicit-atomic-properties.h>
#include <warnings/implicit-fallthrough.h>
#include <warnings/implicit-retain-self.h>
#include <warnings/inherits-via-dominance.h>
#include <warnings/inline.h>
#include <warnings/int-conversion.h>
#include <warnings/invalid-offsetof.h>
#include <warnings/is-defined-to-be.h>
#include <warnings/layout-changed.h>
#include <warnings/missing-braces.h>
#include <warnings/missing-field-initializers.h>
#include <warnings/missing-noreturn.h>
#include <warnings/missing-prototypes.h>
#include <warnings/name-length-exceeded.h>
#include <warnings/narrowing-conversions.h>
#include <warnings/newline-eof.h>
#include <warnings/no-such-warning.h>
#include <warnings/non-virtual-dtor.h>
#include <warnings/not-inlined.h>
#include <warnings/objc-missing-property-synthesis.h>
#include <warnings/objc-root-class.h>
#include <warnings/object-layout-change.h>
#include <warnings/old-style-cast.h>
#include <warnings/overloaded-virtual.h>
#include <warnings/padded.h>
#include <warnings/parentheses.h>
#include <warnings/pedantic.h>
#include <warnings/pointer-sign.h>
#include <warnings/protocol.h>
#include <warnings/receiver-is-weak.h>
#include <warnings/return-type.h>
#include <warnings/selector.h>
#include <warnings/shadow.h>
#include <warnings/shift-sign-overflow.h>
#include <warnings/shorten-64-to-32.h>
#include <warnings/sign-compare.h>
#include <warnings/sign-conversion.h>
#include <warnings/signed-unsigned-compare.h>
#include <warnings/special-members.h>
#include <warnings/static-ctor-not-thread-safe.h>
#include <warnings/strict-selector-match.h>
#include <warnings/switch.h>
#include <warnings/switch-enum.h>
#include <warnings/this-used-in-init.h>
#include <warnings/undeclared-selector.h>
#include <warnings/undef.h>
#include <warnings/uninitialized.h>
#include <warnings/unknown-pragmas.h>
#include <warnings/unreachable-code.h>
#include <warnings/unreachable-code-return.h>
#include <warnings/unreferenced-inline.h>
#include <warnings/unsafe-conversion.h>
#include <warnings/unused-but-set-variable.h>
#include <warnings/unused-function.h>
#include <warnings/unused-label.h>
#include <warnings/unused-parameter.h>
#include <warnings/unused-value.h>
#include <warnings/unused-variable.h>
#include <warnings/used-but-marked-unused.h>
#include <warnings/user-ctor-required.h>
#include <warnings/weak-vtables.h>
