//  :copyright: (c) 2014 Ruslan Baratov.
//  :copyright: (c) 2017 Alex Huszagh.
//  :license: BSD-2, see LICENSE.md for more details.
/*
 *  \addtogroup Warnings
 *  \brief Pop error suppression.
 */

// MACROS
// ------

#if !defined(WARNINGS_PUSH)
#   error Must push before popping error suppression.
#endif

#if defined(WARNINGS_HAVE_CLANG)
#   pragma clang diagnostic pop
#endif

#if defined(WARNINGS_HAVE_GCC)
#   pragma GCC diagnostic pop
#endif

#if defined(WARNINGS_HAVE_MSVC)
#   pragma warning(pop)
#endif

// CLEANUP
// -------

#undef WARNINGS_PUSH
#undef WARNINGS_ARC_BRIDGE_CASTS_DISALLOWED_IN_NONARC
#undef WARNINGS_ARC_REPEATED_USE_OF_WEAK
#undef WARNINGS_ASSIGN_BASE_INACCESSIBLE
#undef WARNINGS_ASSIGN_COULD_NOT_BE_GENERATED
#undef WARNINGS_AUTOMATIC_INLINE
#undef WARNINGS_BEHAVIOR_CHANGE
#undef WARNINGS_BOOL_CONVERSION
#undef WARNINGS_CXX11_EXTENSIONS
#undef WARNINGS_CXX98_COMPAT
#undef WARNINGS_CXX98_COMPAT_PEDANTIC
#undef WARNINGS_CAST_ALIGN
#undef WARNINGS_CATCH_SEMANTIC_CHANGED
#undef WARNINGS_CONDITIONAL_UNINITIALIZED
#undef WARNINGS_CONSTANT_CONDITIONAL
#undef WARNINGS_CONSTANT_CONVERSION
#undef WARNINGS_CONVERSION
#undef WARNINGS_CONVERSION_LOSS
#undef WARNINGS_CONVERSION_SIGN_EXTENDED
#undef WARNINGS_COPY_CTOR_COULD_NOT_BE_GENERATED
#undef WARNINGS_DEPRECATED
#undef WARNINGS_DEPRECATED_DECLARATIONS
#undef WARNINGS_DEPRECATED_IMPLEMENTATIONS
#undef WARNINGS_DEPRECATED_OBJC_ISA_USAGE
#undef WARNINGS_DEPRECATED_REGISTER
#undef WARNINGS_DFLT_CTOR_BASE_INACCESSIBLE
#undef WARNINGS_DFLT_CTOR_COULD_NOT_BE_GENERATED
#undef WARNINGS_COVERED_SWITCH_DEFAULT
#undef WARNINGS_DIGRAPHS_NOT_SUPPORTED
#undef WARNINGS_DISABLED_MACRO_EXPANSION
#undef WARNINGS_DOCUMENTATION
#undef WARNINGS_DOCUMENTATION_UNKNOWN_COMMAND
#undef WARNINGS_DUPLICATE_METHOD_MATCH
#undef WARNINGS_EMPTY_BODY
#undef WARNINGS_ENUM_CONVERSION
#undef WARNINGS_EXIT_TIME_DESTRUCTORS
#undef WARNINGS_EXPLICIT_OWNERSHIP_TYPE
#undef WARNINGS_EXTRA_SEMI
#undef WARNINGS_FORCE_NOT_INLINED
#undef WARNINGS_FORMAT
#undef WARNINGS_FOUR_CHAR_CONSTANTS
#undef WARNINGS_GLOBAL_CONSTRUCTORS
#undef WARNINGS_ILL_FORMED_COMMA_EXPR
#undef WARNINGS_IMPLICIT_ATOMIC_PROPERTIES
#undef WARNINGS_IMPLICIT_FALLTHROUGH
#undef WARNINGS_IMPLICIT_RETAIN_SELF
#undef WARNINGS_INHERITS_VIA_DOMINANCE
#undef WARNINGS_INT_CONVERSION
#undef WARNINGS_INVALID_OFFSETOF
#undef WARNINGS_IS_DEFINED_TO_BE
#undef WARNINGS_LAYOUT_CHANGED
#undef WARNINGS_MISSING_BRACES
#undef WARNINGS_MISSING_FIELD_INITIALIZERS
#undef WARNINGS_MISSING_NORETURN
#undef WARNINGS_MISSING_PROTOTYPES
#undef WARNINGS_NAME_LENGTH_EXCEEDED
#undef WARNINGS_NARROWING_CONVERSIONS
#undef WARNINGS_NEWLINE_EOF
#undef WARNINGS_NON_VIRTUAL_DTOR
#undef WARNINGS_NOT_ENOUGH_PARAMETERS_FOR_MACRO
#undef WARNINGS_NOT_INLINED
#undef WARNINGS_NO_SUCH_WARNING
#undef WARNINGS_OBJC_MISSING_PROPERTY_SYNTHESIS
#undef WARNINGS_OBJC_ROOT_CLASS
#undef WARNINGS_OBJECT_LAYOUT_CHANGE
#undef WARNINGS_OLD_STYLE_CAST
#undef WARNINGS_OVERLOADED_VIRTUAL
#undef WARNINGS_PADDED
#undef WARNINGS_PARENTHESES
#undef WARNINGS_PEDANTIC
#undef WARNINGS_POINTER_SIGN
#undef WARNINGS_PROTOCOL
#undef WARNINGS_RECEIVER_IS_WEAK
#undef WARNINGS_RETURN_TYPE
#undef WARNINGS_SELECTOR
#undef WARNINGS_SHADOW
#undef WARNINGS_SHIFT_SIGN_OVERFLOW
#undef WARNINGS_SHORTEN_64_TO_32
#undef WARNINGS_SIGNED_UNSIGNED_COMPARE
#undef WARNINGS_SIGN_COMPARE
#undef WARNINGS_SIGN_CONVERSION
#undef WARNINGS_STATIC_CTOR_NOT_THREAD_SAFE
#undef WARNINGS_STRICT_SELECTOR_MATCH
#undef WARNINGS_SWITCH
#undef WARNINGS_SWITCH_ENUM
#undef WARNINGS_THIS_USED_IN_INIT
#undef WARNINGS_UNDECLARED_SELECTOR
#undef WARNINGS_UNDEF
#undef WARNINGS_UNEVALUATED_EXPRESSION
#undef WARNINGS_UNINITIALIZED
#undef WARNINGS_UNKNOWN_PRAGMAS
#undef WARNINGS_UNREACHABLE_CODE
#undef WARNINGS_UNREACHABLE_CODE_RETURN
#undef WARNINGS_UNREFERENCED_INLINE
#undef WARNINGS_UNSAFE_CONVERSION
#undef WARNINGS_UNUSED_BUT_SET_VARIABLE
#undef WARNINGS_UNUSED_FUNCTION
#undef WARNINGS_UNUSED_LABEL
#undef WARNINGS_UNUSED_PARAMETER
#undef WARNINGS_UNUSED_VALUE
#undef WARNINGS_UNUSED_VARIABLE
#undef WARNINGS_USED_BUT_MARKED_UNUSED
#undef WARNINGS_USER_CTOR_REQUIRED
#undef WARNINGS_WEAK_VTABLES
